name: Test

on:
  # プルリクが作られた・更新されたとき
  pull_request:
    types: [opened, synchronize]
  # mainブランチがプッシュされたとき
  push: { branches: [main] }

env:
  # さっき決めたいい感じの Secrets の名前
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          # 走らせるプロジェクトのパス
          - NuGetImporterForUnity
        unityVersion:
          # 使う Unity のバージョン
          - 2022.3.7f1
        testMode:
          # 実行するテストのモード
          - editmode
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: webbertakken/unity-test-runner@v1.7
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
